urban_driver_planner:
  _target_: nuplan.planning.simulation.planner.ml_planner.ml_planner.MLPlanner
  _convert_: 'all'
  _recursive_: False

  model_config: ${urban_driver_model} # Dictionary key from existing planner model config (e.g. raster_model)
  checkpoint_path: ${oc.env:NUPLAN_EXP_ROOT}/checkpoints/urbandriver_checkpoint.ckpt  # Path to trained model checkpoint

