closed_loop_reactive_agents_weighted_average:
  _target_: interplan.planning.metrics.aggregator.interplan_weighted_average_metric_aggregator.InterplanWeightedAverageMetricAggregator
  name: 'closed_loop_reactive_agents_weighted_average'
  metric_weights:  # Below we list the metrics used in the scenario scoring function and their corresponsing weights to calculate a weighted average score for each scenario,
  # if not specified, the weight is set as default.
    # metric name : metric weight in the weighted average function
    ego_progress_along_expert_route: 5.0 # This metric has the highest weight equal to 5.0 in the weighted average function, its base score can take a value in [0,1] depending on the ratio of ego to expert progress
    time_to_collision_within_bound: 5.0 # This metric has the highest weight equal to 5.0 in the weighted average function, its base score can be 0 or 1 depending on the minimum time to collision threshold
    lane_changes_to_goal: 4.0 # This metric has a weight equal to 4.0 in the weighted average function, its base score can take a value in [0,1]
    speed_limit_compliance: 4.0 # This metric has a weight equal to 4.0 in the weighted average function, its base score can take a value in [0,1] depending on the amount and duration of over-speeding
    ego_is_comfortable: 2.0 # This metric has the lowest weight equal to 2.0 in the weighted average function, its base score can be 0 or 1 depending on the comfort thresholds on acceleration, jerk and yaw.
    default: 1.0
  file_name: closed_loop_reactive_agents_weighted_average_metrics_${now:${date_format}}
  # The scenario score is defined as the weighted average score of the metrics listed above, multiplied by the score of the multiple_metrics below.
  multiple_metrics:
    default:
      - no_ego_at_fault_collisions # This metric score can be 0, 0.5 or 1 depending on whether there is an at fault collision with VRUs, vehicles or objects
      - drivable_area_compliance # This metric score can be 0 or 1 depending on whether ego drives outside the drivable area
      - ego_is_making_progress # This metric score can be 0 or 1 depending on whether ego makes progress more than a minimum threshold compared to expert's progress
      - driving_direction_compliance # This metric score can be 0 or 0.5 or 1 depending on how much ego drives in the opposite direction if any
    approaching_construction_zone:
      - no_ego_at_fault_collisions # This metric score can be 0, 0.5 or 1 depending on whether there is an at fault collision with VRUs, vehicles or objects
      - drivable_area_compliance # This metric score can be 0 or 1 depending on whether ego drives outside the drivable area
      - ego_is_making_progress # This metric score can be 0 or 1 depending on whether ego makes progress more than a minimum threshold compared to expert's progress
      - ego_sorts_construction_zone
    overtake_parked_vehicle:
      - no_ego_at_fault_collisions # This metric score can be 0, 0.5 or 1 depending on whether there is an at fault collision with VRUs, vehicles or objects
      - drivable_area_compliance # This metric score can be 0 or 1 depending on whether ego drives outside the drivable area
      - ego_is_making_progress # This metric score can be 0 or 1 depending on whether ego makes progress more than a minimum threshold compared to expert's progress
      - ego_sorts_stopped_vehicle
    avoid_crashed_cars:
      - no_ego_at_fault_collisions # This metric score can be 0, 0.5 or 1 depending on whether there is an at fault collision with VRUs, vehicles or objects
      - drivable_area_compliance # This metric score can be 0 or 1 depending on whether ego drives outside the drivable area
      - ego_is_making_progress # This metric score can be 0 or 1 depending on whether ego makes progress more than a minimum threshold compared to expert's progress
      - ego_sorts_stopped_vehicle
    nudge_around_parked_vehicle:
      - no_ego_at_fault_collisions # This metric score can be 0, 0.5 or 1 depending on whether there is an at fault collision with VRUs, vehicles or objects
      - drivable_area_compliance # This metric score can be 0 or 1 depending on whether ego drives outside the drivable area
      - ego_is_making_progress # This metric score can be 0 or 1 depending on whether ego makes progress more than a minimum threshold compared to expert's progress
      - ego_sorts_stopped_vehicle
    jaywalking_pedestrian:
      - no_ego_at_fault_collisions # This metric score can be 0, 0.5 or 1 depending on whether there is an at fault collision with VRUs, vehicles or objects
      - drivable_area_compliance # This metric score can be 0 or 1 depending on whether ego drives outside the drivable area
      - ego_is_making_progress # This metric score can be 0 or 1 depending on whether ego makes progress more than a minimum threshold compared to expert's progress
      - driving_direction_compliance # This metric score can be 0 or 0.5 or 1 depending on how much ego drives in the opposite direction if any
      - ego_sorts_jaywalking_pedestrian

  scenario_type_weights:
    standard_modified_nuplan_scenario: 1
    low_traffic_density: 1
    medium_traffic_density: 1
    high_traffic_density: 1
    overtake_parked_vehicle: 1
    approaching_construction_zone: 1
    jaywalking_pedestrian: 1
    nudge_around_parked_vehicle: 1
    avoid_crashed_cars: 1
  challenge_name: null
