time_to_collision_within_bound_statistics:
  _target_: interplan.planning.metrics.evaluation_metrics.common.lane_changes_to_goal.LaneChangesToGoalStatistics
  _convert_: 'all'
  name: 'lane_changes_to_goal'
  category: 'Planning'

    
